name: motor_mouth
description: A Flutter-based Text-to-Speech (TTS) application that acts as a front-end to a TTS synthesis server. It allows users to input text, select from a list of available speakers, control the speed of the generated speech, and toggle advanced features like SSML. The app also includes an audio visualizer that displays when audio is playing, and supports both immediate playback and asynchronous batch processing of synthesis jobs.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  animated_custom_dropdown: ^3.1.1
  audioplayers: ^6.5.0
  bloc: ^9.0.0
  dartz: ^0.10.1
  device_preview: ^1.3.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_soloud: ^3.2.1
  get_it: ^8.0.3
  http: ^1.4.0
  intl: ^0.20.2
  provider: ^6.1.5

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true

  shaders:
    - shaders/visualizer.frag
